server:
  port: 9091
dubbo:
  application:
    name: search_service
  registry:
    address: zookeeper://192.168.59.131:2181
  protocol:
    port: 20881
    name: dubbo
  consumer:
    check: false
spring:
  data:
    solr:
      host: http://192.168.59.131:8080/solr
  rabbitmq:
    host: 192.168.59.131
    username: admin
    password: admin
    virtual-host: /admin